CREATE TABLE Genre(
genre_id INTEGER NOT NULL AUTO_INCREMENT KEY,
genre VARCHAR(255),
title_id INTEGER,

INDEX USING BTREE (genre),
CONSTRAINT FOREIGN KEY (title_id)
REFERENCES Title (title_id)
ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;